// Generated by CoffeeScript 1.7.1

/*
	generator-joomla-admin-template

	test-load.coffee

	@author Sean
	
	@note Created on 2014-05-27 by PhpStorm
	@note uses Codoc
	@see https://github.com/coffeedoc/codo
 */

(function() {
  "use strict";
  var assert;

  assert = require("assert");

  describe("joomla-admin-template generator", function() {
    return it("can be imported without blowing up", function() {
      var app;
      app = require("../app");
      return assert(app !== undefined);
    });
  });

}).call(this);

//# sourceMappingURL=test-load.map
