// Generated by CoffeeScript 1.7.1

/*
	<%= name %>

	_template.coffee

	@package     Joomla.Administrator
	@subpackage  Templates.<%= _.slugify(name) %>
	@copyright   Copyright (C) 2005 - 2014 <%= license %>
	@license     <%= license %>
	@since       3.0
 */

(function() {
  var initBootstrap;

  initBootstrap = function() {
    var $accordions, $alerts, $dropdowns, $modals, $tabs, $tooltips, $typeaheads;
    $dropdowns = $(".dropdown-toggle").dropdown();
    $accordions = $(".collapse").collapse("show");
    $modals = $("#myModal").modal("hide");
    $typeaheads = $(".typeahead").typeahead();
    $tabs = $(".tabs").button();
    $tooltips = $(".tip").tooltip();
    return $alerts = $(".alert-message").alert();
  };

  jQuery(document).ready(function() {});

}).call(this);

//# sourceMappingURL=_template.map
