// Generated by CoffeeScript 1.7.1

/*
	generator-joomla-admin-template

	index.coffee

	@author Sean
	
	@note Created on 2014-05-27 by PhpStorm
	@note uses Codoc
	@see https://github.com/coffeedoc/codo
 */

(function() {
  "use strict";
  var JoomlaAdminTemplateGenerator, chalk, path, util, yeoman, yosay;

  util = require("util");

  path = require("path");

  yeoman = require("yeoman-generator");

  yosay = require("yosay");

  chalk = require("chalk");

  JoomlaAdminTemplateGenerator = yeoman.generators.Base.extend({
    init: function() {
      this.pkg = require("../package.json");
      return this.on("end", function() {
        if (!this.options["skip-install"]) {
          return this.installDependencies();
        }
      });
    },
    askFor: function() {
      var done, prompts;
      done = this.async();
      this.log(yosay("Welcome to the marvelous JoomlaAdminTemplate generator!"));
      prompts = [
        {
          name: "description",
          message: "Describe your component",
          "default": "A sample description"
        }, {
          name: "name",
          message: "What's the template's name?",
          "default": "default-value"
        }, {
          name: "authorName",
          message: "What's your name?",
          "default": "Author name"
        }, {
          name: "authorEmail",
          message: "What's your e-mail?",
          "default": "email@somedomain.com"
        }, {
          name: "authorURL",
          message: "What's your website?",
          "default": "somedomain.com"
        }, {
          name: "license",
          message: "What's the copyright license?",
          "default": "MIT"
        }, {
          type: "confirm",
          name: "includejQuery",
          message: "Use jQuery?"
        }, {
          type: "confirm",
          name: "includeModernizr",
          message: "Use modernizr?"
        }, {
          type: "confirm",
          name: "sassBoilerplate",
          message: "Use my sass boilerplate to quickly create base styles?"
        }
      ];
      return this.prompt(prompts, (function(props) {
        this.description = props.description;
        this.name = props.name;
        this.authorName = props.authorName;
        this.authorEmail = props.authorEmail;
        this.authorURL = props.authorURL;
        this.license = props.license;
        this.requireManageRights = props.requireManageRights;
        this.sassBoilerplate = props.sassBoilerplate;
        this.includejQuery = props.includejQuery;
        this.includeModernizr = props.includeModernizr;
        this.currentDate = "September 11, 2003";
        return done();
      }).bind(this));
    },
    app: function() {
      this.mkdir("app");
      this.mkdir("app/templates");
      this.template("_package.json", "package.json");
      return this.template("_bower.json", "bower.json");
    },
    projectfiles: function() {
      this.copy("editorconfig", ".editorconfig");
      return this.copy("jshintrc", ".jshintrc");
    },
    createLanguageFiles: function() {
      this.template("language/en-GB/_en-GB.tpl_template-name.ini", "languages/en-GB/en-GB.tpl_" + this._.slugify(this.name) + ".ini");
      return this.template("language/en-GB/_en-GB.tpl_template-name.sys.ini", "languages/en-GB/en-GB.tpl_" + this._.slugify(this.name) + ".sys.ini");
    },
    createTemplateInfoFiles: function() {
      return this.template("_templateDetails.xml", "templateDetails.xml");
    },
    createRootPHPFiles: function() {
      return this.template("_index.php", "index.php");
    },
    createEmptyMVCFolders: function() {
      var folders;
      folders = ["css", "scripts", "styles", "html", "bower_components"];
      return folders.forEach((function(_this) {
        return function(folderName) {
          _this.mkdir(folderName);
          return _this.template("_index.html", folderName + "/index.html");
        };
      })(this));
    }
  });

  module.exports = JoomlaAdminTemplateGenerator;

}).call(this);

//# sourceMappingURL=index.map
